# src/main/resources/application.yml
spring:
  profiles:
    include: aws  # application-aws.yml? ????
  threads:
    virtual:
      enabled: true

ai:
  server:
    url: http://localhost:8000  # ??? ?? AI ?? ??? ????.